sudo: false

language: python

env:
    global:
    # Doctr deploy key for GuQiangJS/finance_tools_py
        # Doctr deploy key for GuQiangJS/finance-tools-py
        - secure: "VjNTVGc37qf6M7gVKnEiS9NhkRb1NPZbh/NdorKgHAGnMSzBAAe4id5Z2zrTG2V6/MNxRXzrIH+kmdgVfeSGrhDFohOcJwKN3gzmthaGthwO5XmOIgnHQ/LUNiVdNhS3Qn2qALskkFaW2f+wraXnIL3bs/PSNzVlYTKapFOGh/A88sjUz8zrgq7wiymE4TU57NWVBkYfl7NqSZF6OOvyEMhtemT5nzJdqNRleQbRpFZMWUPl6G95qmWSBUtdH6HA+wZlFzNlMY+YwWE68mA4oJtaZWr4Z6pAv17afJ4O815ZC6EZ2nNDBwGWFM98cWJO7ER/rJ6HVB0g7rIW+jq1Fu/obmYRGoVNZ8bXHCapqWTqeVFNksJRa5WDblnF0XwwtqJ+e5KAEvGZ44+9fHhixfWnozSMhF0iYOWSVedW78lgJCivRQmuED9uy/XkZLeL/m6ebaYw05lMRu3xjGEYNU3srF/Kx69vrmvJtHWXuIpjTuT1bshjE6U5rvSF8g3BAeu5qa3x3d8wNVjk2fZiRU9MpgDisTFsiwL6N0/qCKPxl0wSQVIiRphdxY+sKS3yiZsTEkz9oPxAAooh0YElnESf4j6JUn07qTwYekv02+7p7/1D/QAhhhVBh/EWQcsmHWLqA4ZzgDcjds23Blcq/NI0962q32SFd4zqgFWtgss="

python:
  - "3.6"

matrix:
    include:
    - python: '3.6'
      env: DOCBUILD=true
before_install:
    - wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    - tar -xzf ta-lib-0.4.0-src.tar.gz
    - cd ta-lib/
    - ./configure --prefix=/usr
    - make
    - sudo make install
    - cd ..
install:
  - pip install coverage
  - pip install pandas
  - pip install numpy
  - pip install coveralls
  - pip install pytest pytest-cov python-coveralls
  - pip install tqdm
  - pip install matplotlib
  - python setup.py install
  - if [[ $DOCBUILD ]]; then
    pip install sphinx sphinx_rtd_theme doctr sphinxcontrib-napoleon;
    fi
before_script:
  - wget -P tests/data https://raw.githubusercontent.com/GuQiangJS/finance-tools-py/master/tests/data/600036.csv
script: 
  pytest --cov=finance_tools_py
after_success:
  - |
      if [[ $DOCBUILD ]]; then
        set -e
        pip install doctr
        cd docs
        make html && make html
        cd ..
        doctr deploy devel --build-tags
      fi
