sudo: false

language: python

env:
    global:
    # Doctr deploy key for GuQiangJS/finance_tools_py
    - secure: "hTJTG5a9UyVLTku9AhXiwcQrcNWeFNr1aFgbZNgLY2hpdIQA7S52ceySAcKepGgNWzy7t3eOelIj+v8D8GIAtXRDK5O3FySBDLibeMaXuF3JYbhByvbK+xtuwwUT789fR+NU2K0zHcdnPnhggTJnTBNOPxBHxVcdrxz3xm4dqk2RtPPNdGIfdqHzuGsQYD9pvN/MVT0xKYuPde3KzBUcQBWqU4ekOu2jDpPjnSAXyn+cH0g1Fo924aivrNThn6KfBaabCtYCDhJUvOYUtigsk0Z7Bj6KCKrAT+hz4S5uq4pHtI4/VOTHSHmCBq4KbEaq8VvsTmpJ3BaStgejhIY5ouxXw27z9w/qcPbZ4/1zNe7LSbVIX8AS9T3zMwgln2ae8RwFZp66JK6JQQApvt2VTief+8B/GALXl50LDMMVYmVLY2pxuUA7z54KHARYrC51oyYNNOmyFVyVnrX3yZA2HJSFg3uvQI/3GsbgIyQhOv9X/unsC1OSKugQG99JTLDPmXzgdmAbN+L13dq9SRdd169xup10d0RDEpZuO7PBY1ZrK++63ZOLyx7s4zzeEZmjKVm1/9342A83Tx7zb7jycHbNbo+AWJHhO4OIs8pmgr14IDV+eGbe7HCxvcVeMCsOLMZbjjeYTI6CJ7ylM6E/88+Onh5M1QJFilSO6BtP4Qs="

python:
  - "3.6"

matrix:
    include:
    - python: '3.6'
      env: DOCBUILD=true
  
install:
  - pip install coverage
  - pip install pandas
  - pip install numpy
  - pip install coveralls
  - python setup.py install
  - if [[ $DOCBUILD ]]; then
    pip install sphinx sphinx_rtd_theme doctr sphinxcontrib-napoleon;
    fi
script: 
  - coverage run -m unittest discover finance_tools_py "test_*.py"
after_success: 
  - coverage report
  - |
      if [[ $DOCBUILD ]]; then
        cd docs
        make html && make html
        cd ..
        doctr deploy devel --build-tags
      fi
  - coveralls
